version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=filmslog-secret-key
      - S3_BUCKET=filmslog-bucket-c49d2ba1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-southeast-1
